"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {Crosshair,Shield,Mountain,Trees,WandSparkles,Target,Users,Settings2,RotateCcw,ScanLine,Plus,X,Check,ChevronRight,LoaderCircle,AlertCircle,ArrowUpRight,Upload,LockKeyhole,Eye,RefreshCw} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Slider} from '@/components/ui/slider';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Skeleton} from '@/components/ui/skeleton';
import {Toaster,toast} from 'sonner';
import {ChampionPicker,Choice,Portrait} from '@/components/draft-controls';
import {api,errorText,fresh,ROLES,LABELS,type Role,type Champion,type Pick,type Draft,type Pool,type Profile,type Status,type Result,type VisionSlot,type Job} from '@/lib/draft';
const ICONS={TOP:Mountain,JUNGLE:Trees,MIDDLE:WandSparkles,BOTTOM:Target,UTILITY:Shield};

// Kept outside the app so typing in a picker's search field never remounts it.
function Team({side,draft,champions,occupied,updatePick}:{side:'allies'|'enemies';draft:Draft;champions:Champion[];occupied:string[];updatePick:(side:'allies'|'enemies',i:number,p:Partial<Pick>)=>void}){
 const friendly=side==='allies';
 return <section className={'team panel '+(friendly?'friendly':'enemy')} aria-label={friendly?'我方阵容':'敌方阵容'}><div className="panel-heading"><span className="eyebrow">{friendly?'YOUR TEAM':'OPPONENTS'}</span><h2>{friendly?'我方阵容':'敌方阵容'}<span>{draft[side].filter(p=>p.champion_id).length} / 5</span></h2></div><div className="team-slots">{draft[side].map((pick,index)=>{const c=champions.find(c=>c.id===pick.champion_id);const own=friendly&&pick.role===draft.role;const Icon=pick.role?ICONS[pick.role]:Crosshair;return <div className={'pick-slot '+(own?'your-slot ':'')+(pick.status==='hover'&&c?'is-hover':'')} key={index}><div className="slot-meta"><span className="role-label"><Icon size={14}/>{friendly?LABELS[pick.role!]:`对手 ${index+1}`}</span>{own?<span className="you-badge">你的位置</span>:c?<span className={'state-label '+pick.status}>{pick.status==='locked'?<LockKeyhole size={11}/>:<Eye size={12}/>} {pick.status==='locked'?'已锁定':'预选'}</span>:null}</div><div className="pick-main"><Portrait champion={c}/><div className="pick-fields"><ChampionPicker champions={champions} value={pick.champion_id} disabledIds={occupied.filter(id=>id!==pick.champion_id)} onChange={id=>updatePick(side,index,{champion_id:id})} label={`${friendly?'我方':'敌方'}第 ${index+1} 位英雄`} placeholder={own?'可选：正在考虑的英雄':'选择英雄…'}/></div></div><div className="slot-options">{!friendly&&<Choice label={`敌方第 ${index+1} 位的位置`} value={pick.role??'unknown'} onChange={v=>updatePick(side,index,{role:v==='unknown'?null:v as Role})} items={[{value:'unknown',label:'位置未知'},...ROLES.map(r=>({value:r,label:LABELS[r]}))]} className="tiny-select"/>}<Choice value={pick.status} onChange={v=>updatePick(side,index,{status:v as Pick['status']})} label={`${friendly?'我方':'敌方'}第 ${index+1} 位选择状态`} items={[{value:'locked',label:'已锁定'},{value:'hover',label:'预选'}]} className="tiny-select"/>{c&&<button className="clear-pick" aria-label={`移除${c.zh}`} onClick={()=>updatePick(side,index,{champion_id:null})}><X size={13}/></button>}</div></div>;})}</div><div className="team-tip">{friendly?'预选按较低权重参与推荐。':'不确定对线位置时，保留“位置未知”。'}</div></section>;
}

export default function DraftApp(){
 const [champions,setChampions]=useState<Champion[]>([]),[status,setStatus]=useState<Status|null>(null);
 const [profile,setProfile]=useState<Profile>({pool:[],statistics:[],account:{}}),[draft,setDraft]=useState<Draft>(fresh);
 const [ready,setReady]=useState(false),[loadError,setLoadError]=useState(''),[result,setResult]=useState<Result|null>(null);
 const [ranking,setRanking]=useState(false),[rankError,setRankError]=useState(''),[revision,setRevision]=useState(0);
 const [profileOpen,setProfileOpen]=useState(false),[settingsOpen,setSettingsOpen]=useState(false),[banOpen,setBanOpen]=useState(false);
 const [visionOpen,setVisionOpen]=useState(false),[visionBusy,setVisionBusy]=useState(false),[visionSlots,setVisionSlots]=useState<VisionSlot[]>([]),[visionError,setVisionError]=useState('');
 const [preview,setPreview]=useState(''),[dragging,setDragging]=useState(false);
 const fileInput=useRef<HTMLInputElement>(null),visionRequest=useRef(0);
 const [poolRole,setPoolRole]=useState<Role>('UTILITY'),[poolHero,setPoolHero]=useState<string|null>(null),[comfort,setComfort]=useState(3),[poolSaving,setPoolSaving]=useState(false);
 const [gameName,setGameName]=useState(''),[tagLine,setTagLine]=useState(''),[syncCount,setSyncCount]=useState('50');
 const [job,setJob]=useState<Job|null>(null),[syncStarting,setSyncStarting]=useState(false);
 const find=useCallback((id:string|null)=>champions.find(c=>c.id===id),[champions]);
 useEffect(()=>{let cancelled=false;Promise.all([api<{champions:Champion[]}>('/champions'),api<Status>('/status'),api<Profile>('/profile')]).then(([catalog,settings,user])=>{if(cancelled)return;setChampions(catalog.champions);setStatus(settings);setProfile(user);setGameName(user.account.game_name??'');setTagLine(user.account.tag_line??'');try{const saved=JSON.parse(sessionStorage.getItem('draft-coach-v1')??'null');if(saved&&ROLES.includes(saved.role)&&[420,440].includes(saved.queue)&&Array.isArray(saved.allies)&&saved.allies.length===5&&Array.isArray(saved.enemies)&&saved.enemies.length===5&&Array.isArray(saved.bans)&&saved.bans.length<=10&&[...saved.allies,...saved.enemies].every((p:Pick)=>p&&(!p.champion_id||catalog.champions.some(c=>c.id===p.champion_id))&&(p.role===null||ROLES.includes(p.role))&&['locked','hover'].includes(p.status))&&saved.bans.every((id:string)=>catalog.champions.some(c=>c.id===id)))setDraft(saved);}catch{}setReady(true);}).catch(e=>!cancelled&&setLoadError(errorText(e)));return()=>{cancelled=true;};},[]);
 const reloadProfile=useCallback(async()=>{const p=await api<Profile>('/profile?queue='+draft.queue);setProfile(p);setRevision(v=>v+1);},[draft.queue]);
 useEffect(()=>{if(ready)reloadProfile().catch(e=>toast.error(errorText(e)));},[ready,reloadProfile]);
 useEffect(()=>{if(!ready)return;try{sessionStorage.setItem('draft-coach-v1',JSON.stringify(draft));}catch{}const controller=new AbortController();setRanking(true);setRankError('');const timer=setTimeout(()=>api<Result>('/recommend',{method:'POST',body:JSON.stringify(draft),signal:controller.signal}).then(data=>{setResult(data);setRanking(false);}).catch(e=>{if(!controller.signal.aborted){setRankError(errorText(e));setResult(null);setRanking(false);}}),180);return()=>{clearTimeout(timer);controller.abort();};},[draft,ready,revision]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 const upload=useCallback(async(file:File)=>{if(visionBusy)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type)){toast.error('请选择 PNG、JPEG 或 WebP 截图');return;}if(file.size>10*1024*1024){toast.error('图片不能超过 10 MB');return;}setVisionOpen(true);setVisionError('');setVisionSlots([]);setPreview(URL.createObjectURL(file));if(!status?.vision_ready){setVisionError('先在项目 .env 中配置 OPENAI_API_KEY 并重启，或使用手动添加 Ban。');return;}setVisionBusy(true);const request=++visionRequest.current;try{const form=new FormData();form.append('file',file);const data=await api<{slots:VisionSlot[]}>('/vision/bans',{method:'POST',body:form});if(request===visionRequest.current){setVisionSlots(data.slots);if(!data.slots.length)setVisionError('没有识别到 Ban 栏，请裁出左上或右上区域后重试。');}}catch(e){if(request===visionRequest.current)setVisionError(errorText(e));}finally{if(request===visionRequest.current)setVisionBusy(false);}},[visionBusy,status]);
 useEffect(()=>{const paste=(e:ClipboardEvent)=>{const file=Array.from(e.clipboardData?.items??[]).find(item=>item.type.startsWith('image/'))?.getAsFile();if(file){e.preventDefault();void upload(file);}};window.addEventListener('paste',paste);return()=>window.removeEventListener('paste',paste);},[upload]);
 useEffect(()=>{if(!job||job.status!=='running')return;let cancelled=false;const timer=setTimeout(async()=>{try{const next=await api<Job>('/riot/sync/'+job.id);if(cancelled)return;setJob(next);if(next.status==='done'){await reloadProfile();toast.success(next.message);}else if(next.status==='error')toast.error(next.message);}catch(e){if(!cancelled){setJob(j=>j?{...j,status:'error',message:errorText(e)}:j);toast.error(errorText(e));}}},1500);return()=>{cancelled=true;clearTimeout(timer);};},[job,reloadProfile]);
 function updatePick(side:'allies'|'enemies',index:number,patch:Partial<Pick>){setDraft(d=>({...d,[side]:d[side].map((p,i)=>i===index?{...p,...patch}:p)}));}
 function addBan(id:string|null){if(!id)return;if(draft.bans.length>=10){toast.error('已达到 10 个 Ban，请先移除错误的英雄');return;}setDraft(d=>d.bans.includes(id)?d:({...d,bans:[...d.bans,id]}));}
 function applyVision(){const ids=visionSlots.filter(s=>s.champion_id&&s.state==='champion').map(s=>s.champion_id!);const selected=new Set([...draft.allies,...draft.enemies].map(p=>p.champion_id));const conflicts=ids.filter(id=>selected.has(id));if(conflicts.length){setVisionError('识别结果与当前已选英雄冲突，请校正：'+conflicts.map(id=>find(id)?.zh).join('、'));return;}const merged=Array.from(new Set([...draft.bans,...ids]));if(merged.length>10){setVisionError('合并后超过 10 个 Ban，请先校正或移除旧的 Ban。');return;}setDraft(d=>({...d,bans:merged}));setVisionOpen(false);toast.success(`已加入 ${merged.length-draft.bans.length} 个 Ban`);}
 async function savePool(){if(!poolHero)return;setPoolSaving(true);try{await api('/pool',{method:'PUT',body:JSON.stringify({champion_id:poolHero,role:poolRole,comfort})});await reloadProfile();setPoolHero(null);toast.success('英雄池已保存');}catch(e){toast.error(errorText(e));}finally{setPoolSaving(false);}}
 async function removePool(p:Pool){try{await api('/pool/'+p.role+'/'+p.champion_id,{method:'DELETE'});await reloadProfile();}catch(e){toast.error(errorText(e));}}
 async function startSync(){setSyncStarting(true);try{setJob(await api<Job>('/riot/sync',{method:'POST',body:JSON.stringify({game_name:gameName.trim(),tag_line:tagLine.trim().replace(/^#/,''),count:Number(syncCount),queue:draft.queue})}));}catch(e){toast.error(errorText(e));}finally{setSyncStarting(false);}}
 const occupied=[...draft.bans,...draft.allies.map(p=>p.champion_id),...draft.enemies.map(p=>p.champion_id)].filter((x):x is string=>!!x);
 const poolCount=profile.pool.filter(p=>p.role===draft.role).length,knownPicks=[...draft.allies,...draft.enemies].filter(p=>p.champion_id).length;
 return <div className="app-shell"><Toaster theme="dark" position="top-center" richColors/>
 <header className="app-header"><div className="brand"><span className="brand-mark"><Crosshair size={25}/></span><div>DRAFT<span className="brand-light">COACH</span><small>你的 BP 搭档</small></div></div><div className="header-actions"><span className="region-pill">NA <span>·</span> {status?.patch??'—'}</span><Button variant="ghost" onClick={()=>{setPoolRole(draft.role);setProfileOpen(true);}}><Users size={16}/><span>我的英雄池</span></Button><Button variant="ghost" size="icon" aria-label="连接设置" onClick={()=>setSettingsOpen(true)}><Settings2 size={18}/></Button></div></header>
 <main><div className="workspace-heading"><div><span className="eyebrow accent-text">CHAMPION SELECT</span><h1>选出适合这一局的英雄<span className="title-dot">.</span></h1></div><Button className="reset-button" variant="ghost" onClick={()=>{setDraft(d=>({...fresh(),role:d.role,queue:d.queue,pool_only:d.pool_only}));visionRequest.current++;setVisionBusy(false);setVisionOpen(false);setVisionSlots([]);setPreview('');toast.success('已开始新的 BP');}}><RotateCcw size={14}/>新一局</Button></div>{loadError&&<div className="error-banner" role="alert"><AlertCircle/>{loadError}<Button onClick={()=>window.location.reload()}>重新连接</Button></div>}
 <div className="draft-toolbar"><div className="role-picker"><span className="muted">我的位置</span><Tabs value={draft.role} onValueChange={r=>setDraft(d=>({...d,role:r as Role}))}><TabsList className="role-tabs">{ROLES.map(r=>{const Icon=ICONS[r];return <TabsTrigger key={r} value={r}><Icon size={16}/>{LABELS[r]}</TabsTrigger>;})}</TabsList></Tabs></div><Choice label="排位队列" value={String(draft.queue)} onChange={v=>setDraft(d=>({...d,queue:Number(v) as 420|440}))} items={[{value:'420',label:'单 / 双排'},{value:'440',label:'灵活排位'}]} className="queue-select"/></div>
 <div className="draft-grid"><Team side="allies" {...{draft,champions,occupied,updatePick}}/><section className="recommendations" aria-label="推荐英雄" aria-busy={ranking}><div className="recommend-heading"><div><span className="eyebrow">YOUR NEXT PICK</span><h2>为你推荐 <span>TOP 5</span></h2></div><span className="recalculate">{ranking?<><LoaderCircle size={13} className="spin"/>更新中</>:<><Check size={13}/>随 BP 更新</>}</span></div>{!poolCount&&<button className="setup-callout" onClick={()=>{setPoolRole(draft.role);setProfileOpen(true);}}><Users size={17}/><span>添加你的{LABELS[draft.role]}英雄池，让推荐更懂你<small>当前使用阵容规则，尚未加入个人熟练度</small></span><ChevronRight size={17}/></button>}<div className="recommend-filter"><span>{knownPicks?`已知 ${knownPicks} 位英雄`:'可以从任意一位英雄开始'}</span><label htmlFor="pool-only">仅我的英雄池 <Switch id="pool-only" checked={draft.pool_only} onCheckedChange={v=>setDraft(d=>({...d,pool_only:v}))}/></label></div>
 {rankError?<div className="error-banner" role="alert"><AlertCircle size={18}/>{rankError}</div>:!result?<div className="loading-cards">{[0,1,2].map(i=><Skeleton key={i} className="loading-card"/>)}<p>准备英雄资料…</p></div>:result.recommendations.length===0?<div className="empty-recommend"><Shield size={32}/><h3>当前没有可推荐的英雄</h3><p>在英雄池中添加{LABELS[draft.role]}英雄，或关闭“仅我的英雄池”。</p><Button onClick={()=>{setPoolRole(draft.role);setProfileOpen(true);}}>编辑英雄池</Button></div>:<div className={'recommend-list '+(ranking?'updating':'')}>{result.recommendations.map((rec,index)=><details className={'recommend-card '+(index===0?'first-choice':'')} key={rec.champion.id} open={index===0?true:undefined}><summary><span className="rank-index">{String(index+1).padStart(2,'0')}</span><Portrait champion={rec.champion} size={index===0?'large':'normal'}/><span className="recommend-name"><b>{rec.champion.zh}</b><small>{rec.champion.name}</small><span className="recommend-short">{rec.reasons.find(r=>!r.startsWith('你的')&&!r.startsWith('该位置'))??rec.reasons[0]}</span></span><span className="score"><b>{rec.score.toFixed(1)}</b><small>适配评分</small></span></summary><div className="recommend-detail"><div className="recommend-stats"><span><b>{rec.comfort?`${rec.comfort}/5`:'未设置'}</b>熟练度</span><span><b>{rec.win_rate===null?'—':`${rec.win_rate}%`}</b>个人胜率</span><span><b>{rec.games||'—'}</b>该位置场次</span></div><div className="score-breakdown" aria-label="评分组成">{Object.entries(rec.components).map(([k,v])=><div key={k}><span>{({personal:'个人表现',composition:'阵容补足',matchup:'敌方应对',synergy:'队友配合'} as Record<string,string>)[k]}</span><b>{v}<small>/{({personal:40,composition:25,matchup:20,synergy:15} as Record<string,number>)[k]}</small></b></div>)}</div><div className="reason-list">{rec.reasons.map((r,i)=><p key={i}><Check size={13}/>{r}</p>)}</div>{rec.risks.length>0&&<div className="risk-note"><AlertCircle size={14}/><span>{rec.risks.slice(0,2).join('；')}</span></div>}</div></details>)}</div>}
 <div className="recommend-footnote"><span className="rule-tag">规则推断</span><p>适配评分不是获胜概率。阵容判断来自技能组规则；个人胜率按当前排位队列、位置与已同步样本统计。</p></div></section><Team side="enemies" {...{draft,champions,occupied,updatePick}}/></div>
 <section className={'ban-panel panel '+(dragging?'drag-active':'')} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node))setDragging(false);}} onDrop={e=>{e.preventDefault();setDragging(false);const file=e.dataTransfer.files[0];if(file)void upload(file);}} aria-label="已禁用英雄与截图导入"><div className="ban-summary"><span className="eyebrow">BANNED</span><h2>已禁用 <small>{draft.bans.length} / 10</small></h2><span className="muted">自动从推荐中排除</span></div><div className="ban-slots">{Array.from({length:10},(_,i)=>{const c=find(draft.bans[i]??null);return <button key={i} className={'ban-slot '+(c?'filled':'')} title={c?`移除 ${c.zh}`:'手动添加 Ban'} aria-label={c?`移除 Ban ${c.zh}`:`添加第 ${i+1} 个 Ban`} onClick={()=>c?setDraft(d=>({...d,bans:d.bans.filter(id=>id!==c.id)})):setBanOpen(true)}>{c?<><img src={c.image} alt={c.zh}/><span className="ban-cross"><X size={15}/></span></>:<Plus size={16}/>}</button>;})}</div><button className="upload-button" onClick={()=>fileInput.current?.click()} disabled={visionBusy}><ScanLine size={21}/><span>{visionBusy?'正在识别…':'拖入 BP 截图'}<small>点击上传 · 支持 ⌘V 粘贴</small></span><Upload size={15}/></button><input type="file" accept="image/png,image/jpeg,image/webp" ref={fileInput} hidden onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></section></main>
 <footer className="app-footer"><span>DRAFT COACH <span className="muted">/</span> PERSONAL EDITION</span><p>Draft Coach is not endorsed by Riot Games and does not reflect the views or opinions of Riot Games or anyone officially involved in producing or managing Riot Games properties. Riot Games and all associated properties are trademarks or registered trademarks of Riot Games, Inc.</p></footer>
 <Dialog open={banOpen} onOpenChange={setBanOpen}><DialogContent className="app-dialog"><DialogHeader><DialogTitle>手动添加 Ban</DialogTitle><DialogDescription>已选和已禁用英雄会自动排除。</DialogDescription></DialogHeader><ChampionPicker champions={champions} value={null} disabledIds={occupied} onChange={id=>{addBan(id);setBanOpen(false);}} label="选择禁用英雄"/></DialogContent></Dialog>
 <Dialog open={visionOpen} onOpenChange={setVisionOpen}><DialogContent className="app-dialog vision-dialog"><DialogHeader><DialogTitle><ScanLine size={20}/> 检查 Ban 识别结果</DialogTitle><DialogDescription>核对头像后应用。看不清的英雄可手动补充，已有 Ban 会保留。</DialogDescription></DialogHeader>{preview&&<img className="screenshot-preview" src={preview} alt="本次上传的 BP 截图"/>}{visionBusy&&<div className="vision-loading"><LoaderCircle className="spin"/>正在辨认 Ban 栏里的英雄…</div>}{visionError&&<div className="error-banner" role="alert"><AlertCircle size={16}/>{visionError}</div>}<div className="vision-results">{visionSlots.map((slot,index)=><div className={'vision-slot '+(slot.state==='uncertain'?'uncertain':'')} key={index}><span className="muted">{slot.side==='left'?'左侧':slot.side==='right'?'右侧':'截图'} {slot.slot+1}<small>{slot.state==='uncertain'?'待确认':slot.state==='empty'?'空 Ban 位':'已识别'}</small></span><ChampionPicker champions={champions} value={slot.champion_id} onChange={id=>setVisionSlots(ss=>ss.map((s,i)=>i===index?{...s,champion_id:id,state:id?'champion':'empty'}:s))} label={`校正第 ${index+1} 个识别结果`} placeholder="选择 / 留空"/></div>)}</div><div className="dialog-actions"><Button variant="outline" onClick={()=>fileInput.current?.click()} disabled={visionBusy}>重新上传</Button><Button disabled={visionBusy||!visionSlots.some(s=>s.champion_id)} onClick={applyVision}>加入 {new Set(visionSlots.filter(s=>s.champion_id).map(s=>s.champion_id)).size} 个 Ban <Check size={15}/></Button></div></DialogContent></Dialog>
 <Dialog open={profileOpen} onOpenChange={setProfileOpen}><DialogContent className="app-dialog profile-dialog"><DialogHeader><DialogTitle>我的英雄池</DialogTitle><DialogDescription>按位置设置你真正会玩的英雄。1 为刚接触，5 为非常熟练。</DialogDescription></DialogHeader><Tabs value={poolRole} onValueChange={r=>{setPoolRole(r as Role);setPoolHero(null);}}><TabsList className="profile-role-tabs">{ROLES.map(r=><TabsTrigger key={r} value={r}>{LABELS[r]}</TabsTrigger>)}</TabsList>{ROLES.map(r=><TabsContent key={r} value={r}><div className="pool-list">{profile.pool.filter(p=>p.role===r).map(p=>{const c=find(p.champion_id),s=profile.statistics.find(s=>s.champion_id===p.champion_id&&s.role===r);return <div className="pool-entry" key={p.champion_id}><Portrait champion={c} size="small"/><span className="pool-entry-name"><b>{c?.zh}</b><small>{s?`${s.games} 场 · ${(s.wins/s.games*100).toFixed(0)}% 胜率`:'暂无已同步战绩'}</small></span><button className="comfort-button" title="点击修改熟练度" onClick={()=>{setPoolHero(p.champion_id);setComfort(p.comfort);}}>{p.comfort}/5</button><Button variant="ghost" size="icon" aria-label={`移除英雄池中的${c?.zh}`} onClick={()=>void removePool(p)}><X size={14}/></Button></div>;})}{!profile.pool.some(p=>p.role===r)&&<p className="empty-pool">还没有添加{LABELS[r]}英雄。</p>}</div></TabsContent>)}</Tabs><div className="pool-editor"><ChampionPicker champions={champions} value={poolHero} onChange={id=>{setPoolHero(id);const existing=profile.pool.find(p=>p.champion_id===id&&p.role===poolRole);setComfort(existing?.comfort??3);}} label="添加到英雄池" placeholder="添加 / 修改英雄"/><div className="comfort-field"><label>熟练度 <b>{comfort}/5</b></label><Slider aria-label="熟练度" value={[comfort]} onValueChange={v=>setComfort(v[0])} min={1} max={5} step={1}/></div><Button onClick={()=>void savePool()} disabled={!poolHero||poolSaving}>{poolSaving?<LoaderCircle className="spin" size={16}/>:<Plus size={16}/>}保存</Button></div><div className="profile-sync"><span><RefreshCw size={14}/> {profile.account.game_name?`${profile.account.game_name}#${profile.account.tag_line}`:'尚未同步 Riot 战绩'}</span><Button variant="ghost" onClick={()=>{setProfileOpen(false);setSettingsOpen(true);}}>同步战绩 <ArrowUpRight size={14}/></Button></div></DialogContent></Dialog>
 <Dialog open={settingsOpen} onOpenChange={setSettingsOpen}><DialogContent className="app-dialog settings-dialog"><DialogHeader><DialogTitle>账号与连接</DialogTitle><DialogDescription>NA 服务器 · 数据保存在本机</DialogDescription></DialogHeader><div className="connection-line"><span><ScanLine size={17}/>截图识别</span><span className={status?.vision_ready?'connected':'muted'}>{status?.vision_ready?'已配置':'待配置'}</span></div>{!status?.vision_ready&&<p className="config-hint">在项目的 <code>.env</code> 中填写 <code>OPENAI_API_KEY</code> 后重启。截图识别通过图片 API 调用。</p>}<div className="connection-line"><span><RefreshCw size={17}/>Riot 战绩</span><span className={status?.riot_ready?'connected':'muted'}>{status?.riot_ready?'已配置':'待配置'}</span></div>{!status?.riot_ready&&<p className="config-hint">在 <code>.env</code> 中填写 <code>RIOT_API_KEY</code> 后重启。可从 <a href="https://developer.riotgames.com/" target="_blank" rel="noreferrer">Riot Developer Portal</a> 获取。</p>}<div className="riot-id-fields"><label>Riot 名称<Input value={gameName} onChange={e=>setGameName(e.target.value)} placeholder="Game name" maxLength={80}/></label><label>标签<Input value={tagLine} onChange={e=>setTagLine(e.target.value)} placeholder="NA1" maxLength={20}/></label></div><div className="sync-options"><Choice value={syncCount} onChange={setSyncCount} label="同步比赛数" items={[{value:'20',label:'最近 20 场'},{value:'50',label:'最近 50 场'},{value:'100',label:'最近 100 场'}]}/><span className="muted">{draft.queue===420?'单 / 双排':'灵活排位'} · 近 90 天</span></div><p className="config-hint">首次同步需要逐场获取数据，可能需要几分钟。以后会复用本机缓存。</p>{job&&<div className={'sync-job '+job.status} role="status">{job.status==='running'?<><LoaderCircle className="spin" size={15}/>已检查 {job.completed} / {job.total||'…'} 场</>:job.message}</div>}<Button onClick={()=>void startSync()} disabled={!status?.riot_ready||!gameName.trim()||!tagLine.trim()||syncStarting||job?.status==='running'}>{syncStarting||job?.status==='running'?<LoaderCircle className="spin" size={15}/>:<RefreshCw size={15}/>}同步我的战绩</Button>{profile.account.synced_at&&<p className="muted sync-timestamp">上次同步：{new Date(profile.account.synced_at*1000).toLocaleString('zh-CN')}</p>}</DialogContent></Dialog>
 </div>;
}
